# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# watersheds_generation.py
# Created on: 2019-03-06 12:49:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
import glob

# Check out the ArcGIS Spatial Analyst extension license
arcpy.CheckOutExtension("Spatial")

# Local variables:
bw_fd = "bw_fd"
bw_fa = "bw_fa"
sp_location = "./pourpoints/"
ws_location = "./watersheds/"

shapefiles_collection = []

for filename in glob.glob(os.path.join("./outlets" , '*.shp')):
    location_name = filename.split("\\")[1].split(".")[0]
    print "Generating watershed for location ", location_name

    # Process: Snap Pour Point
    arcpy.gp.SnapPourPoint_sa(filename, bw_fa, sp_location + "sp_" + location_name, "50", "station")

    # Process: Watershed
    arcpy.gp.Watershed_sa(bw_fd, sp_location + "sp_" + location_name, ws_location + "rs_" + location_name, "")

    # Process: Raster to Polygon
    arcpy.RasterToPolygon_conversion(ws_location + "rs_" + location_name, ws_location + "ws_" + location_name +
                                     ".shp", "SIMPLIFY", "VALUE", "SINGLE_OUTER_PART", "")

    shapefiles_collection.append(ws_location + "ws_" + location_name + ".shp")

    print "ws_" + location_name + ".shp is generated"

arcpy.Merge_management(shapefiles_collection, "./watersheds/final_watersheds")

print "Merged all generated watersheds as one shapefile 'final_watersheds'"


